var exemplo = [  
   {  
      "Id":"card-id-1",
      "Nome":"Exemplo1",
      "Edicao":"ex1",
      "Tipo":"ex1",
      "Cmc":"1",
      "Ilustrador":"exemplar1",
      "Cores":[  
         {  
            "id":"check-azul",
            "isChecked":false
         },
         {  
            "id":"check-branco",
            "isChecked":false
         },
         {  
            "id":"check-preto",
            "isChecked":true
         },
         {  
            "id":"check-verde",
            "isChecked":false
         },
         {  
            "id":"check-vermelho",
            "isChecked":true
         }
      ]
   },
   {  
      "Id":"card-id-2",
      "Nome":"Exemplo2",
      "Edicao":"ex2",
      "Tipo":"ex2",
      "Cmc":"2",
      "Ilustrador":"Exemplar2",
      "Cores":[  
         {  
            "id":"check-azul",
            "isChecked":true
         },
         {  
            "id":"check-branco",
            "isChecked":true
         },
         {  
            "id":"check-preto",
            "isChecked":false
         },
         {  
            "id":"check-verde",
            "isChecked":true
         },
         {  
            "id":"check-vermelho",
            "isChecked":false
         }
      ]
   }
]